# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	#database
	config.vm.define "database" do |db|
		db.vm.box = "ubuntu/xenial64"
		db.vm.provider "virtualbox" do |vb|
			vb.memory = "512"
		db.vm.hostname = "db01"
		db.vm.network "private_network", ip: "192.168.55.100"
		db.vm.synced_folder "./db", "/home/vagrant/db"
		db.vm.provision "shell", inline: <<-SHELL
			#install mysql server
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
			sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
			sudo apt-get -y install mysql-server

			#install ssh service
			sudo apt-get install openssh-server
			sudo service ssh start

			#create db directory for filesync
			sudo mkdir db

			#install ufw
			sudo apt-get install ufw -y
			sudo ufw -f enable

			#create rules
			sudo ufw allow from any to any port 3306
			sudo ufw allow from any to any port 22


			SHELL
	end

end
	#webserver
	config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip:"192.168.55.101"
		web.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
		web.vm.synced_folder "./www", "/var/www/html"
		web.vm.provision "shell", inline: <<-SHELL
			#install apache service
			sudo apt-get update
			sudo apt-get -y install apache2

			#install ufw
			sudo apt-get install ufw -y
			sudo ufw -f enable

			#create rules
			sudo ufw allow 80/tcp
			sudo ufw allow from any to any port 22

		SHELL
		web.vm.provider "virtualbox" do |vb|
	  	vb.memory = "512"
		end
	end

 end
