version: "3.3"

services:

  pihole:
      container_name: pihole
      image: pihole/pihole:latest
      ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "67:67/udp"
        - "80:80/tcp"
        - "443:443/tcp"
      environment:
        TZ: 'Europe/Zurich'
        WEBPASSWORD: '1234'
      volumes:
        - './etc-pihole/:/etc/pihole/'
        - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      dns:
        - 127.0.0.1
        - 1.1.1.1
      restart: unless-stopped

      #cpus: 1
      #mem_limit: 1024m


  db:
    image: mysql:5.7
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dbteset
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 1234
    ports:
      - "9906:3306"
    #cpus: 1
    #mem_limit: 1024m


  web:
    image: php:7.2.2-apache
    container_name: php_web
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
      
    #cpus: 1
    #mem_limit: 1024m


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
        - db:db
    ports:
        - 8080:80
    restart: on-failure
    environment:
        MYSQL_ROOT_PASSWORD: 1234
    #cpus: 1
    #mem_limit: 1024m

# monitoring gui
  cadvisor:
    image: google/cadvisor:v0.29.0
    container_name: cadvisor
    command: -storage_driver_db=cadvisor
    restart: on-failure
    ports:
      - "8888:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    #cpus: 1
#mem_limit: 1024m