# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    #config.vm.network "forwarded_port", guest: 80, host: 1234
    config.vm.network "private_network", type: "dhcp"
    config.vm.synced_folder ".", "/docker_dl", nfs: true
    
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"  
    end
  end
